/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CONECTA4_H_RPCGEN
#define _CONECTA4_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define OK_NAME_REGISTERED 10000
#define ERROR_NAME_REPEATED 10001
#define ERROR_SERVER_FULL 10002
#define ERROR_PLAYER_NOT_FOUND 10003
#define TURN_MOVE 70001
#define TURN_WAIT 70002
#define GAMEOVER_WIN 50052
#define GAMEOVER_DRAW 50053
#define GAMEOVER_LOSE 50054
#define BOARD_WIDTH 7
#define BOARD_HEIGHT 6
#define BOARD_CELLS 42
#define PLAYER_1_CHIP 111
#define PLAYER_2_CHIP 120
#define EMPTY_CELL 32
#define STRING_LENGTH 128

typedef char tBoard[BOARD_CELLS];

typedef char tString[STRING_LENGTH];

enum tPlayer {
	player1 = 0,
	player2 = 1,
};
typedef enum tPlayer tPlayer;

enum tMove {
	OK_move = 0,
	fullColumn_move = 1,
};
typedef enum tMove tMove;

struct tMessage {
	tString msg;
};
typedef struct tMessage tMessage;

struct tColumn {
	u_int column;
	tString player;
};
typedef struct tColumn tColumn;

struct tBlock {
	u_int code;
	tString msg;
	tBoard board;
};
typedef struct tBlock tBlock;

#define CONECTA4 99
#define CONECTA4VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define registerPlayer 1
extern  int * registerplayer_1(tMessage *, CLIENT *);
extern  int * registerplayer_1_svc(tMessage *, struct svc_req *);
#define getGameStatus 2
extern  tBlock * getgamestatus_1(tMessage *, CLIENT *);
extern  tBlock * getgamestatus_1_svc(tMessage *, struct svc_req *);
#define insertChipInBoard 3
extern  tBlock * insertchipinboard_1(tColumn *, CLIENT *);
extern  tBlock * insertchipinboard_1_svc(tColumn *, struct svc_req *);
extern int conecta4_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registerPlayer 1
extern  int * registerplayer_1();
extern  int * registerplayer_1_svc();
#define getGameStatus 2
extern  tBlock * getgamestatus_1();
extern  tBlock * getgamestatus_1_svc();
#define insertChipInBoard 3
extern  tBlock * insertchipinboard_1();
extern  tBlock * insertchipinboard_1_svc();
extern int conecta4_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_tBoard (XDR *, tBoard);
extern  bool_t xdr_tString (XDR *, tString);
extern  bool_t xdr_tPlayer (XDR *, tPlayer*);
extern  bool_t xdr_tMove (XDR *, tMove*);
extern  bool_t xdr_tMessage (XDR *, tMessage*);
extern  bool_t xdr_tColumn (XDR *, tColumn*);
extern  bool_t xdr_tBlock (XDR *, tBlock*);

#else /* K&R C */
extern bool_t xdr_tBoard ();
extern bool_t xdr_tString ();
extern bool_t xdr_tPlayer ();
extern bool_t xdr_tMove ();
extern bool_t xdr_tMessage ();
extern bool_t xdr_tColumn ();
extern bool_t xdr_tBlock ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CONECTA4_H_RPCGEN */
